### ISSUE TITLE
Process does not conclude with 5 raster

### ISSUE THREAD

**Issue by bellanz80** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#1]
Hello, first of all I congratulate you. It was months that I was looking for a way to run AHP with QGIS! Your complement came as a gift of the year 2020!
I am having trouble using 5 raster layers. The process seems to be using CPU and memory, but after 20 minutes, it doesn't conclude. They are rasters of dimensions that I do not think can generate that much time. I would like to ask, if it is a failure of my computer, or the times are indeed very long.
With 3 files (of the same 5), it took about 2 minutes.
Thank you very much for your support!

Windows 10 64 bit
QGIS 3.12.2 - New Profile

![image](https://user-images.githubusercontent.com/38449926/82596763-7e3eb200-9b6d-11ea-8330-eb3e8378b8e1.png)

**Comment by romariocarvalhoneto** [comment]
Thanks @bellanz80 . I'm glad I could help. 
On the tests we run, the time consuming tasks happened when working with large rasters and many classes in the rasters. The plugin was built to warn the user if he has more than 50 classes in a raster (which is a lot for this kind of analysis) and also built to not let the user load more than 100 (way too much) what would couse this problem you are having. I would like to ask of you to run with 3 of the 5, and then run with 3 again, but now with the remainder 2 plus another one of the first 3. Since you said it took about 2 minutes to do it, we will know if is is working. If it does the job for the two sets of 3 raster each, try with a set of 4 rasters and see if the problem still. If it is working, it will probably work for the 5 together as well. Also pay attention to the instruction on size and other things of rasters. They must be matching to run. But if they are not matching, it will not run even for 2 rasters.
Please let me know if it worked.

**Comment by bellanz80** [comment]
Hello! Thank you very much, everything was successful. It was probably my mistake.
I have a question: of the 5 rasters, I have noticed that 3 have a vertical pixel of 3014, and the others have 3015 as a vertical pixel.
I do not know this difference, since the clip was made with the same polygon.
But, that difference of 1 vertical pixel, can generate problems or errors?
Many thanks!

-

**Comment by romariocarvalhoneto** [comment]
@bellanz80 the rasters are arrays of values. If they are different in size, the arrays will not match each other. That's why it will not work. But thank you to report your error. I may add some step on the logic to ensure the rasters match each other and warn the user before it runs.

**Comment by bellanz80** [comment]
Many thank's!
