### ISSUE TITLE
QGIS 3.14 DON'T LOAD LAYER

### ISSUE THREAD

**Issue by bellanz80** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#5]
Hi, there is a problem with QGIs 3.14: the plugin does not load any TOC layer.
Thank's!

Luca

windows 10 64 bit
QGIS 3.12 / 3.14

![image](https://user-images.githubusercontent.com/38449926/85968259-33913080-b98a-11ea-9573-f0b2fa0206e8.png)

**Comment by romariocarvalhoneto** [comment]
Thank you so much for your feedback. I will look what is going on.

**Comment by romariocarvalhoneto** [comment]
I did report as a QGIS bug (https://github.com/qgis/QGIS/issues/37686#issue-653407903) since the code is working on the previous versions of QGIS. May be something related to the new version of QGIS, which is not a LTR.

**Comment by romariocarvalhoneto** [comment]
I just closed by mistake. Reopened.

**Comment by nyalldawson** [comment]
This isn't an upstream bug. You need to edit your .UI file and change

    <header>qgsmaplayercombobox.h</header>

To

    <header>qgis.gui</header>

**Comment by romariocarvalhoneto** [comment]
Thank you @nyalldawson , but didn't work. So than I looked into the code and found the problem. But I don't know why this happened. Maybe if you know, please tell us. I will explain how it was corrected:
It's the way the code was written. When I first added a QgsMapLayerComboBox, I also added the commands to add their names into the comboBox as we can see on lines 344 and 345 and I needed to clean it first (line 342): 
![old_code](https://user-images.githubusercontent.com/52353524/86991282-12dc8e00-c175-11ea-83c7-eaf824785c37.PNG)
 And it was working perfectly fine until QGIS 3.14. But now it was not loading the names because of my clear() command (line 342). If I removed this line, it worked but with twice as much layers. So than I notice that was not necessary to add their names into the comboBox because it would load by itself. So I commented the corresponding lines and now is working again:
![new_code](https://user-images.githubusercontent.com/52353524/86991614-ed03b900-c175-11ea-8296-a9d21ff08ee3.PNG)
Do you know by the way why is this happening?

**Comment by nyalldawson** [comment]
That's not how QgsMapLayerComboBox should be used. You're treating it like a generic QComboBox there and adding work for yourself :D

All you need to do is construct the QgsMapLayerComboBox, and it will automatically populate with the current layers (and react to newly added/renamed/dropped layers for you). You can optionally set filters on the widget to restrict the layers shown in the combo.

**Comment by romariocarvalhoneto** [comment]
@nyalldawson Thanks again. I did notice that now as I fixed the bug but I just don't understand why worked before and now it doesn't, at the specific QGIS 3.14 version.
If I may, I would like to ask of you about the right way of "asking for help". At the end, was a code error and not an upstream bug, which I wrongly did report it. What should I have done? How should I properly get help to solve this kind of problem? Please, let consider a "real problem" and not a basic code error like mine.

**Comment by bellanz80** [comment]
Hi. Y I have updated the plug to 0.3. the same error occurs.
again clean installation of QGIS 3.14, windows 10

![image](https://user-images.githubusercontent.com/38449926/87238324-c1c3d880-c3c6-11ea-8f39-63407b54edbc.png)

**Comment by romariocarvalhoneto** [comment]
I have sent the updated version 0.4.1 to the QGIS repository and we are just waiting to be approved.
The master version found here in github should be working.

**Comment by nyalldawson** [comment]
@romariocarvalhoneto 

> If I may, I would like to ask of you about the right way of "asking for help". At the end, was a code error and not an upstream bug, which I wrongly did report it. What should I have done? How should I properly get help to solve this kind of problem? Please, let consider a "real problem" and not a basic code error like mine.

The best way is via the qgis developer mailing list: https://lists.osgeo.org/mailman/listinfo/qgis-developer

**Comment by romariocarvalhoneto** [comment]
Thanks @nyalldawson.

**Comment by romariocarvalhoneto** [comment]
Thanks @bellanz80 for your support. The plugin was updated in the QGIS repository and is now working.
