### ISSUE TITLE
Broken plugin

### ISSUE THREAD

**Issue by ghtmtt** [romariocarvalhoneto/Weighted-Multi-Criteria-Analysis---WMCA#9]
Hi,

cannot try the plugin due to an error:

```
This plugin is broken
Error reading metadata: general
```

Cheers and thanks

**Comment by romariocarvalhoneto** [comment]
Thank you @ghtmtt . I deleted this version 0.4 and now the 0.3 is available and working.
The problem was due to a #'comment' that I erased wrongly on the metadata file as I show here:
![metadata](https://user-images.githubusercontent.com/52353524/87172585-d6ab4980-c2aa-11ea-8bd4-e8e71cf4b539.PNG)
The bottom one was uncommented, while it should be commented as we see now in the screenshot and as it was on the previous versions.
